// flow-typed signature: ffe84fd957355f84a468d66d2483dccd
// flow-typed version: <<STUB>>/@babel/plugin-syntax-flow_v^7.2.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-flow/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-flow/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-flow/lib'>;
}
declare module '@babel/plugin-syntax-flow/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-flow/lib'>;
}
